language: go

go:
  - 1.8.3
  - 1.9

before_install:
  - sudo add-apt-repository ppa:masterminds/glide -y
  - sudo apt-get update -q
  - sudo apt-get install glide -y

install:
  - glide install

script:
  - go test $(glide novendor)
